apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: team-e-prod
  namespace: team-e
spec:
  releaseName: team-e-prod
  chart:
    git: https://github.com/sameeraman/gitops-helm.git
    path: hello-arc-helm
    ref: master
  values:
    image:
      repository: liorkamrat/hello-arc
      tag: latest
      port: 8080
    replicaCount: 3
    env:
      name: MESSAGE
      value: This application is deployed using Azure ARC GitOps Helm Charts!
    service:
      type: NodePort
      port: 80
      targetPort: 8080